name: Release

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  cut-release:
    name: runner / cut-release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

  tag-major:
    name: runner / tag-major
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'release'
    steps:
      - uses: actions/checkout@v2
      - run: |
          VERSION=`echo ${{ github.event.release.tag_name }} | cut -d. -f1`
          git tag -f "${VERSION}"
          git push -f --tags
