name: Review Dog

on: [pull_request]

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: github-pr-review
          path: image
          pattern: "*.sh"
          exclude: "./.git/*"
